[versions]
agp = "9.1.1"
kotlin = "2.4.10"
coreKtx = "1.19.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.11.0"
lifecycleViewmodelKtx = "2.11.0"
appcompat = "1.8.0"
constraintlayout = "2.2.2"
recyclerview = "1.4.0"
exoplayer = "2.19.1"
ffmpegkit = "2.2.1"
material = "1.14.0"
lottie = "6.7.1"
aboutlibraries = "14.2.1"
aboutlibrariescore = "15.2.0"
gson = "2.14.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
exoplayer-core = { group = "com.google.android.exoplayer" , name="exoplayer-core", version.ref = "exoplayer"}
exoplayer-ui = { group = "com.google.android.exoplayer" , name="exoplayer-ui", version.ref = "exoplayer"}
ffmpeg-kit-full-gpl = { group = "com.antonkarpenko" , name="ffmpeg-kit-full-gpl", version.ref = "ffmpegkit"}
google-material = { group = "com.google.android.material" , name="material", version.ref = "material"}
lottie = { group = "com.airbnb.android" , name="lottie", version.ref = "lottie"}
about-libraries = { group = "com.mikepenz" , name="aboutlibraries", version.ref = "aboutlibraries"}
about-libraries-core = { group = "com.mikepenz" , name="aboutlibraries-core", version.ref = "aboutlibrariescore"}
gson = { group = "com.google.code.gson" , name="gson", version.ref = "gson"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

